# Spring Boot configuration
spring:
  # Allows circular references
  main:
    allow-circular-references: true
  # Develop part
  profiles:
    active: development
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myanalista
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true # Spring Boot configuration
  #Config size of upload file
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # Change size default of pagination
  data:
    rest:
      default-page-size: 20
  #Config Email
  mail:
    host: email-smtp.us-east-2.amazonaws.com
    port: 587
    username: AKIAVHMEDDNN5WO6QQZC
    password: fyqxbDgZSXhNG0NncZTKgObZCYRm40rQVHB/Vics
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# Server configuration
server:
  port: 8080 #set your port

cloud:
  aws:
    credentials:
      access-key: AKIAVHMEDDNN5WO6QQZC
      secret-key: fyqxbDgZSXhNG0NncZTKgObZCYRm40rQVHB/Vics
    region:
      static: us-east-2
    stack:
      auto: false

springdoc:
  pathsToMatch: /v1/**
  swagger-ui:
    use-root-path: true